POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Teste novooooo",
    "details": "Descrição do evento",
    "maximumAttendees": 2
}


### 

POST http://localhost:3333/events/62bf347d-5bd6-47f7-9a31-9ab887673fba/attendees
Content-Type: application/json

{
    "name": "Pimennnta, Raphaelllldddddl",
    "email": "pimentaaaa@tfffeeeest.com"
}


###

GET http://localhost:3333/events/62bf347d-5bd6-47f7-9a31-9ab887673fba


###


GET http://localhost:3333/attendees/17/badge


###

GET http://localhost:3333/attendees/17/check-in


###
GET http://localhost:3333/events/62bf347d-5bd6-47f7-9a31-9ab887673fba/attendees?query=Raphael