POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Teste novo",
    "details": "Descrição do evento",
    "maximumAttendees": 2
}


### 

POST http://localhost:3333/events/1c24a239-0667-4601-b285-f03e71c6c0a4/attendees
Content-Type: application/json

{
    "name": "Pimennnta, Raphaelllll",
    "email": "pimentaaaa@teeeest.com"
}


###

GET http://localhost:3333/events/1c24a239-0667-4601-b285-f03e71c6c0a4


###


GET http://localhost:3333/attendees/1/badge